### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by ztwaaa** [gongminmin/AIHoloImager#33]
CMake Error: File ../AIHoloImager/cmakeFindModules/OpenMVGConfig.cmake.in does not exist.
CMake Error at External/openMVG/openMVG/src/CMakeLists.txt:617 (configure_file):
  configure_file Problem configuring file

**Comment by ztwaaa** [comment]
I changed CMakeLists.txt:617 to configure_file("${CMAKE_SOURCE_DIR}/External/openMVG/openMVG/src/cmakeFindModules/OpenMVGConfig.cmake.in".Now,it works

**Comment by gongminmin** [comment]
No, that manual change is not necessary. The real reason is the patches under External/openMVG/Patches are not applied. Most likely it's because your git is not configured well, like missing user name or email.
